const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),net=require('node:net');
const {chromium}=require('C:/Users/kevle/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const check=(ok,message)=>{if(!ok)throw Error(message)};
(async()=>{const directory=fs.mkdtempSync(path.resolve('artifacts/magic-browser-'));for(const name of fs.readdirSync('BaldursGateStyleOblivion').filter(n=>n.endsWith('.json')))fs.copyFileSync(path.join('BaldursGateStyleOblivion',name),path.join(directory,name));
 const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
 const server=spawn('dotnet',['tools/ActorResearch/bin/Debug/net10.0/ActorResearch.dll','edit','--no-open','--port',String(port),'--config',path.join(directory,'actor-classification.json')]);let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);let browser;
 try{for(let i=0;i<60;i++){try{if((await fetch(`http://127.0.0.1:${port}/magic`)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}/magic`);await page.waitForFunction(()=>document.querySelectorAll('#kitRows tr').length>0);
 check(await page.locator('#casterProfile option').count()===7,'Seven caster profiles');await page.locator('#casterProfile').selectOption('Conjurer');await page.locator('#casterTier').selectOption('5');await page.waitForFunction(()=>document.querySelector('#casterLevel').value==='20'&&document.querySelector('#casterStats').textContent.includes('"Conjuration": 100'));
 check(await page.locator('#kitRows').textContent().then(s=>s.includes('Master Daedric summon')),'Conjurer primary mastery kit');check(await page.locator('#casterStats').textContent().then(s=>!s.includes('"Destruction": 100')),'Conjurer does not prioritize Destruction');
 await page.locator('#casterProfile').selectOption('Destruction specialist');await page.waitForFunction(()=>document.querySelector('#casterStats').textContent.includes('"Destruction": 100'));
 await page.getByText('Equipment, resistance and observed resource overrides',{exact:true}).click();const before=await page.locator('#metrics').textContent();await page.locator('#resistance').fill('50');await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('Attack 50 damage'));check(await page.locator('#metrics').textContent()!==before,'Resistance changes damage');
 await page.locator('#casterTier').selectOption('8');await page.locator('#rareAccess').check();await page.waitForFunction(()=>document.querySelector('#kitRows').textContent.includes('Exceptional Fire attack'));
 await page.locator('#casterLevel').fill('15');await page.waitForFunction(()=>document.querySelector('#casterStats').textContent.includes('"Destruction": 82'));check(await page.locator('#kitRows').textContent().then(s=>!s.includes('Exceptional')),'Level-adjusted skills gate rare spells');
 await page.locator('#castInterval').fill('2');await page.locator('#saveMagic').click();await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('Saved.'));check(JSON.parse(fs.readFileSync(path.join(directory,'magic.json'))).CastInterval===2,'Configuration saved');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#castInterval').value==='2'&&document.querySelectorAll('#kitRows tr').length>0);
 const request=await page.request.post(`http://127.0.0.1:${port}/api/magic/config`,{data:{Json:'{}',Revision:'invalid'}});check(request.status()===403,'Unauthorized config request rejected');
 check(!errors.length,errors.join('\n'));await page.screenshot({path:'artifacts/magic-first-pass/workbench.png',fullPage:false});console.log('Magic browser checks passed: profiles, tier/level stats, kit access, resistance, config save/reload and request protection.');
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});