const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),net=require('node:net');
const {chromium}=require('C:/Users/kevle/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const check=(ok,msg)=>{if(!ok)throw Error(msg)};
(async()=>{
 const directory=fs.mkdtempSync(path.resolve('artifacts/economy-browser-'));for(const name of fs.readdirSync('BaldursGateStyleOblivion').filter(n=>n.endsWith('.json')))fs.copyFileSync(path.join('BaldursGateStyleOblivion',name),path.join(directory,name));
 const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));const origin=`http://127.0.0.1:${port}`;const server=spawn('dotnet',['tools/ActorResearch/bin/Debug/net10.0/ActorResearch.dll','edit','--no-open','--port',String(port),'--config',path.join(directory,'actor-classification.json')]);let browser,log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
 try{
  for(let i=0;i<100;i++){try{if((await fetch(origin+'/economy')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
  browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/economy');await page.waitForFunction(()=>document.querySelectorAll('#cards .card').length===5,{},{timeout:30000}).catch(async err=>{console.log(await page.locator('#status').textContent());throw err});check(!errors.length,errors.join('\n'));
  check(await page.locator('.editor-nav a[aria-current=page]').textContent()==='Economy','Economy navigation selected');check(await page.locator('#tier').inputValue()==='2'&&await page.locator('#level').inputValue()==='5','Quick tier maps to level');
  await page.locator('#tier').selectOption('4');await page.waitForFunction(()=>document.querySelector('#level').value==='15');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Analysis updated'));await page.locator('#level').fill('20');await page.locator('#level').dispatchEvent('change');await page.waitForFunction(()=>preview?.Defaults?.Stats?.Blade===100);check(await page.locator('#tier').inputValue()==='4','Level adjusts independently of tier');
  const post=async(route,body)=>page.evaluate(async({route,body})=>{const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json','X-Actor-Editor-Token':TOKEN},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}},{route,body});
  const d=await(await fetch(origin+'/api/economy')).json();const request={Settings:d.Settings,Scenario:{Tier:2,Level:5,Class:'Warrior',Category:'Bandit',Outing:'Short outing',Target:'0229BA:Oblivion.esm'},CraftedValueMultiplier:d.CraftedValueMultiplier,IngredientFloor:d.IngredientFloor};const before=await post('/api/economy/preview',request);check(before.status===200,'Baseline API preview');request.Scenario.CarryWeight=0;const noCarry=await post('/api/economy/preview',request);check(noCarry.data.Proposed.MedianProfit<before.data.Proposed.MedianProfit,'Capacity affects income');request.Scenario.CarryWeight=null;request.Scenario.OtherExpenses=100;const expenses=await post('/api/economy/preview',request);check(Math.abs(expenses.data.Proposed.MedianProfit-before.data.Proposed.MedianProfit+100)<.0001,'Expenses affect net profit');
  for(const cls of d.Classes){request.Scenario.Class=cls;const r=await post('/api/economy/preview',request);check(r.status===200,'Quick class works: '+cls+' '+JSON.stringify(r.data.error))}request.Scenario.Class='Warrior';
  await page.getByRole('button',{name:'Item prices',exact:true}).click();await page.locator('#search').fill('Steel Longsword');check(await page.locator('#items tr').count()>0,'Price search works');await page.locator('#items button[data-edit]').first().click();await page.locator('#overrideValue').fill('123');await page.locator('#applyOverride').click();await page.waitForFunction(()=>document.querySelector('#items').textContent.includes('123'));await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved.'));const saved=JSON.parse(fs.readFileSync(path.join(directory,'economy.json')));check(Object.values(saved.ItemOverrides).some(p=>p.Value===123),'Exact price exception saved');
  const stale=await post('/api/economy/config',{Json:JSON.stringify(d.Settings),Revision:d.Revision,AlchemyRevision:d.AlchemyRevision,CraftedValueMultiplier:d.CraftedValueMultiplier,IngredientFloor:d.IngredientFloor});check(stale.status===409,'Stale save rejected');
  await page.getByRole('button',{name:'Crafting & spells',exact:true}).click();await page.locator('#crafted').fill('.19');await page.locator('#crafted').dispatchEvent('change');await page.waitForFunction(()=>document.querySelector('#craftRows').textContent.includes('22'));await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved.'));check(JSON.parse(fs.readFileSync(path.join(directory,'alchemy.json'))).CraftedValueMultiplier===.19,'Crafted value saves to canonical alchemy configuration');
  await page.getByRole('button',{name:'Prices & services',exact:true}).click();check(await page.locator('#gmsts tr').count()===10,'Engine controls available with reasons');check(await page.locator('#priceTables input').count()>50,'Material, category, slot, prestige and soul-gem controls');
  await page.getByRole('button',{name:'Merchant capacity',exact:true}).click();check(await page.locator('#merchantProfiles tr').count()>10,'Merchant profiles configurable');await page.locator('#merchantSearch').fill('Seed');check(await page.locator('#merchantRows tr').count()>0,'Merchant filtering');
  await page.getByRole('button',{name:'Outing analyzer',exact:true}).click();await page.screenshot({path:'artifacts/economy-workbench.png',fullPage:false});await page.setViewportSize({width:480,height:900});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile layout fits viewport');await page.screenshot({path:'artifacts/economy-mobile.png',fullPage:false});
  const forbidden=await page.request.post(origin+'/api/economy/config',{data:{Json:'{}'}});check(forbidden.status()===403,'Writes require editor request authorization');check(!errors.length,errors.join('\n'));console.log('Economy browser checks passed: quick builds, all classes, live loot/carry/cost calculations, price overrides, shared alchemy save, stale revisions, native controls, merchant profiles, responsive layout and request protection.');
 }finally{await browser?.close();server.kill()}
})().catch(e=>{console.error(e);process.exitCode=1});
