<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <!-- Turned off for Mo2 compatibility -->
    <CETCompat>false</CETCompat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Oblivion" Version="0.54.4" />
    <PackageReference Include="Mutagen.Bethesda.Synthesis" Version="0.36.6" />
  </ItemGroup>
  <ItemGroup><None Update="creature-lists.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><None Update="actor-classification.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><None Update="geography.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
<ItemGroup><None Update="dungeons.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
</Project>

