using BaldursGateStyleOblivion.Classification;
using BaldursGateStyleOblivion.Core;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;

namespace BaldursGateStyleOblivion;

public class Program
{
    private static Lazy<PatcherSettings> settings = null!;

    public static async Task<int> Main(string[] args) => await SynthesisPipeline.Instance
        .AddPatch<IOblivionMod, IOblivionModGetter>(RunPatch)
        .SetAutogeneratedSettings("Settings", "settings.json", out settings)
        .SetTypicalOpen(GameRelease.Oblivion, "BaldursGateStyleOblivion.esp")
        .Run(args);

    public static void RunPatch(IPatcherState<IOblivionMod, IOblivionModGetter> state)
    {
        using var run = new PatcherRun(state, settings.Value);
        try
        {
            run.Log($"Loaded {state.LoadOrder.Count} plugins.");
            var profiles = new Dictionary<FormKey, ActorProfile>();
            run.Module("Actor classification", run.Settings.EnableActorClassification, false,
                () => profiles = ActorClassification.Write(state, run));
            run.Module("Diagnostics", run.Settings.EnableDiagnostics, false, () =>
            {
                ActorReports.Write(state, run);
                Diagnostics.DiagnosticReports.Write(state, profiles, run);
            });
            run.Log("Completed. No gameplay transformation modules are implemented yet.");
        }
        catch (Exception exception)
        {
            run.Log($"Failed: {exception}");
            throw;
        }
    }
}

