using BaldursGateStyleOblivion.Classification;
using BaldursGateStyleOblivion.Core;
using BaldursGateStyleOblivion.Modules;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;

namespace BaldursGateStyleOblivion;

public class Program
{
    private static Lazy<PatcherSettings> settings = null!;

    public static async Task<int> Main(string[] args)
    {
        // Avoid opening the installed output: its binary overlay would lock the file during writing.
        var loadOrderIndex = Array.FindIndex(args, value => value is "-l" or "--LoadOrderFilePath");
        var outputIndex = Array.FindIndex(args, value => value is "-o" or "--OutputPath");
        string? temporaryLoadOrder = null;
        try
        {
            if (args.Contains("run-patcher") && loadOrderIndex >= 0 && outputIndex >= 0
                && loadOrderIndex + 1 < args.Length && outputIndex + 1 < args.Length)
            {
                var outputName = Path.GetFileName(args[outputIndex + 1]);
                var plugins = File.ReadAllLines(args[loadOrderIndex + 1]);
                temporaryLoadOrder = Path.GetTempFileName();
                File.WriteAllLines(temporaryLoadOrder, plugins.Where(line =>
                    !string.Equals(line.Trim().TrimStart('*'), outputName, StringComparison.OrdinalIgnoreCase)));
                args[loadOrderIndex + 1] = temporaryLoadOrder;
            }
            QuestConditionRepair.Reset();
            var result = await SynthesisPipeline.Instance
                .AddPatch<IOblivionMod, IOblivionModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out settings)
                .SetTypicalOpen(GameRelease.Oblivion, "BaldursGateStyleOblivion.esp")
                .Run(args);
            if (result == 0 && outputIndex >= 0 && outputIndex + 1 < args.Length)
            {
                var repaired = QuestConditionRepair.Apply(args[outputIndex + 1]);
                if (repaired > 0) Console.WriteLine($"Remapped {repaired} quest-condition references to the output masters.");
            }
            return result;
        }
        finally
        {
            if (temporaryLoadOrder is not null) File.Delete(temporaryLoadOrder);
        }
    }

    public static void RunPatch(IPatcherState<IOblivionMod, IOblivionModGetter> state)
    {
        using var run = new PatcherRun(state, settings.Value);
        try
        {
            run.Log($"Loaded {state.LoadOrder.Count} plugins.");
            var actorSettings = run.Settings.EnableActorClassification ? ActorClassification.LoadSettings(run) : new ClassificationSettings();
            var profiles = new Dictionary<FormKey, ActorProfile>();
            run.Module("Actor classification", run.Settings.EnableActorClassification, false,
                () => profiles = ActorClassification.Write(state, run, actorSettings));
            var changes = new Dictionary<FormKey, string[]>();
            run.Module("Actor deleveling", run.Settings.EnableActorDeleveling && run.Settings.EnableActorClassification, false,
                () => changes = ActorDeleveling.Run(state, profiles, actorSettings, run));
            run.Module("Creature list deleveling", run.Settings.EnableCreatureListDeleveling, false, () =>
            {
                foreach (var change in CreatureListDeleveling.Run(state, profiles, run)) changes.Add(change.Key, change.Value);
            });
            run.Module("Geographic discovery", run.Settings.EnableGeographicDiscovery, false,
                () => { foreach (var change in GeographicDiscovery.Run(state, profiles, run)) changes[change.Key] = change.Value; });
            run.Module("Equipment distribution", run.Settings.EnableEquipmentDistribution, false,
                () => { foreach (var change in EquipmentDistributionModule.Run(state, profiles, run))
                    changes[change.Key] = changes.GetValueOrDefault(change.Key, []).Concat(change.Value).Distinct().ToArray(); });
            run.Module("World loot", run.Settings.EnableWorldLoot, false,
                () => { foreach (var change in WorldLoot.Run(state, profiles, run))
                    changes[change.Key] = changes.GetValueOrDefault(change.Key, []).Concat(change.Value).Distinct().ToArray(); });
            run.Module("Merchant stock", run.Settings.EnableMerchantStock, false,
                () => { foreach (var change in MerchantStock.Run(state, run))
                    changes[change.Key] = changes.GetValueOrDefault(change.Key, []).Concat(change.Value).Distinct().ToArray(); });
            run.Module("Quest rewards and artifacts", run.Settings.EnableQuestRewards, false,
                () => { foreach (var change in QuestRewards.Run(state, run))
                    changes[change.Key] = changes.GetValueOrDefault(change.Key, []).Concat(change.Value).Distinct().ToArray(); });
            run.Module("Physical combat", run.Settings.EnablePhysicalCombatAnalysis || run.Settings.EnablePhysicalCombatBalance, false,
                () => { foreach (var change in Combat.PhysicalCombatModule.Run(state, profiles, run))
                    changes[change.Key] = changes.GetValueOrDefault(change.Key, []).Concat(change.Value).Distinct().ToArray(); });
            run.Module("Magic gameplay",run.Settings.EnableMagicBalance,false,()=>
            {
                foreach(var change in Magic.MagicBalanceModule.Run(state,run))
                    changes[change.Key]=changes.GetValueOrDefault(change.Key,[]).Concat(change.Value).Distinct().ToArray();
            });
            run.Module("Enchantments and alchemy",run.Settings.EnableEnchantmentBalance||run.Settings.EnableAlchemyBalance,false,()=>
            {
                foreach(var change in Enhancements.EnhancementModule.Run(state,run))
                    changes[change.Key]=changes.GetValueOrDefault(change.Key,[]).Concat(change.Value).Distinct().ToArray();
            });
            run.Module("Magic analysis",run.Settings.EnableMagicAnalysis,false,()=>Magic.MagicAnalysisModule.Run(state,run));
            run.Module("Diagnostics", run.Settings.EnableDiagnostics, false, () =>
            {
                ActorReports.Write(state, run);
                Diagnostics.DiagnosticReports.Write(state, profiles, run, changes);
            });
            run.Module("Record discovery", run.Settings.EnableRecordDiscovery && run.Settings.EnableDiagnostics, false,
                () => Discovery.RecordDiscovery.Write(state, run));
            run.Log($"Completed. {changes.Count} records modified; ReportOnly={run.Settings.ReportOnly}.");
        }
        catch (Exception exception)
        {
            run.Log($"Failed: {exception}");
            throw;
        }
    }
}
