using BaldursGateStyleOblivion.Classification;
using BaldursGateStyleOblivion.Core;
using BaldursGateStyleOblivion.Modules;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;

namespace BaldursGateStyleOblivion;

public class Program
{
    private static Lazy<PatcherSettings> settings = null!;

    public static async Task<int> Main(string[] args)
    {
        // Avoid opening the installed output: its binary overlay would lock the file during writing.
        var loadOrderIndex = Array.FindIndex(args, value => value is "-l" or "--LoadOrderFilePath");
        var outputIndex = Array.FindIndex(args, value => value is "-o" or "--OutputPath");
        string? temporaryLoadOrder = null;
        try
        {
            if (args.Contains("run-patcher") && loadOrderIndex >= 0 && outputIndex >= 0
                && loadOrderIndex + 1 < args.Length && outputIndex + 1 < args.Length)
            {
                var outputName = Path.GetFileName(args[outputIndex + 1]);
                var plugins = File.ReadAllLines(args[loadOrderIndex + 1]);
                temporaryLoadOrder = Path.GetTempFileName();
                File.WriteAllLines(temporaryLoadOrder, plugins.Where(line =>
                    !string.Equals(line.Trim().TrimStart('*'), outputName, StringComparison.OrdinalIgnoreCase)));
                args[loadOrderIndex + 1] = temporaryLoadOrder;
            }
            return await SynthesisPipeline.Instance
                .AddPatch<IOblivionMod, IOblivionModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out settings)
                .SetTypicalOpen(GameRelease.Oblivion, "BaldursGateStyleOblivion.esp")
                .Run(args);
        }
        finally
        {
            if (temporaryLoadOrder is not null) File.Delete(temporaryLoadOrder);
        }
    }

    public static void RunPatch(IPatcherState<IOblivionMod, IOblivionModGetter> state)
    {
        using var run = new PatcherRun(state, settings.Value);
        try
        {
            run.Log($"Loaded {state.LoadOrder.Count} plugins.");
            var actorSettings = run.Settings.EnableActorClassification ? ActorClassification.LoadSettings(run) : new ClassificationSettings();
            var profiles = new Dictionary<FormKey, ActorProfile>();
            run.Module("Actor classification", run.Settings.EnableActorClassification, false,
                () => profiles = ActorClassification.Write(state, run, actorSettings));
            var changes = new Dictionary<FormKey, string[]>();
            run.Module("Actor deleveling", run.Settings.EnableActorDeleveling && run.Settings.EnableActorClassification, false,
                () => changes = ActorDeleveling.Run(state, profiles, actorSettings, run));
            run.Module("Diagnostics", run.Settings.EnableDiagnostics, false, () =>
            {
                ActorReports.Write(state, run);
                Diagnostics.DiagnosticReports.Write(state, profiles, run, changes);
            });
            run.Module("Record discovery", run.Settings.EnableRecordDiscovery && run.Settings.EnableDiagnostics, false,
                () => Discovery.RecordDiscovery.Write(state, run));
            run.Log($"Completed. {changes.Count} actor records modified; ReportOnly={run.Settings.ReportOnly}.");
        }
        catch (Exception exception)
        {
            run.Log($"Failed: {exception}");
            throw;
        }
    }
}


